### ISSUE TITLE
userManagment.listAuthFactors

### ISSUE THREAD

**Issue by ArifAA14** [workos/workos-node#1016]
Hey

I have recently migrated a small internal application to Work OS, I am trying to currently implement a MFA using totp, but unfortunately the documentation is severely lacking some crucial information.

So I am using NextJS (still on the pages router instead of the app), from my understanding the flow of MFA in workOS goes like this 

1. Enroll a user in MFA
2. Display the QR Code and let users scan through an authenticator app.
3. Challenge the factor
4. Verify the factor

While all this makes sense and I managed to put together an implementation that works but the issue is 

```
 const challenge = await workos.mfa.challengeFactor({
      authenticationFactorId: mfaId,
    })
```

So this doesn't make any sense at all? the `authenticationFactorId` will change everytime a new enrollment is done, how can I possibly keep track of it? 

In the docs, I also came across the following 

```
  const user = await workos.userManagement.listAuthFactors({
    userId,
  })
```

I have tried using this method several times but I end up with the following error 

```
UnprocessableEntityException: The following requirement must be met:
        property userId should not exist
```

**Comment by PaulAsjes** [comment]
Hey @ArifAA14, the flow you mentioned is almost correct. A more accurate description would be:

1. Enrol user in MFA
2. Display the QR Code and let users scan through an authenticator app
3. Authenticate with the TOTP

The challenge step would only come when a user that's already enrolled with MFA tries to log in with a password but gets the `mfa_challenge` error.

I agree that the docs aren't where they should be when it comes to MFA, however you might find the AuthKit example app useful to see how the flow works: https://github.com/workos/authkit/tree/main/src/app/using-your-own-ui/mfa

**Comment by ArifAA14** [comment]
Hey @PaulAsjes, thank you for getting back and the example did help a lot!

I managed to implement it somehow, so many thanks for all the help
