### ISSUE TITLE
Session module for all platforms

### ISSUE THREAD

**Issue by rougsig** [workos/workos-node#1110]
Description:
Currently, codebase contains duplicated session management logic across different platforms/frameworks.

Remix: https://github.com/workos/authkit-remix/blob/main/src/session.ts
NextJS: https://github.com/workos/authkit-nextjs/blob/main/src/session.ts

But there is no repos for express, fastify, etc.

Proposal:
Extract the common session management logic into a workos-node (this repo). Then, implement lightweight adapters for each specific platform/framework (Express, Fastify, Next.js, Remix) that interface with this core module.

Benefits:
Simplifies the process of adding support for new platforms by only requiring the creation of new adapters.

My goal:
I need an adapter for fastify. For now i will go to copy NextJs sources and adapt it for fastify. It will be better, if I can call workos-node methods to encypt/decrypt session, validate access token, etc. In easy words give me the core logic for session auth.

**Comment by rougsig** [comment]
cc https://github.com/workos/workos-node/pull/1105

**Comment by PaulAsjes** [comment]
Hey there, this is actually currently in the works: https://github.com/workos/workos-node/pull/1105

In the meanwhile there are some helper methods within workos-node that you should be able to use. See the [Quick Start](https://workos.com/docs/user-management/3-handle-the-user-session/b-manually) for examples on how to use those helper methods.

I'll keep this open till we merge the new Session helper class.

**Comment by rougsig** [comment]
@PaulAsjes great! Do you have any ETA to release that?

**Comment by PaulAsjes** [comment]
We're in the process of testing it, hoping to release it sometime next week.

**Comment by PaulAsjes** [comment]
https://github.com/workos/workos-node/pull/1105 has released as 7.25.0. An update to the docs is coming next week, in the meanwhile you can check out the gist in that PR for an example on how to use the new session helpers.

**Comment by rougsig** [comment]
@PaulAsjes Is it possible to seal some additional application data to cookie? Should I open an new issue for that?

**Comment by PaulAsjes** [comment]
Can you elaborate on your use case? Any reason why you'd want to add data to the sealed cookie over storing it in a new one?

**Comment by rougsig** [comment]
I can easily encode and decode two session (workos and my extra user metadata) cookies. There is no problem. 

I trying to make that logic:
1. User sign-ins in to app.
2. Do some app related stuff
3. User does not enters to the app 3days. Mark session as stale, and require user to sign-in again.
4. If user work in app every day, do not sign-out they.

With WorkOS, I should to define session TTL (7 days by default). WorkOS haven't any abilities to extend session.
For now, I have plan to set WorkOS session TTL to 10years. And encode to session cookie my TTL (3days). After every access token refresh app will update session cookie TTL (to 3 days).

NOTES: Session cookie TTL, it's extra field, NOT a browser cookie maxAge.

If user trying to use app with expired cookie, app will send expire-session request to WorkOS, and require user to sign-in again.
