### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by oskarwilliams** [workos/workos-node#1149]
# Overview

We have seen a few cases in the past month where our calls to list events has resulted in an `Unexpected error: TypeError: fetch failed `. It would be very useful if you could add the cause to this error so that it would propagate through and allow us to see what the error is, and whether it is solvable on our end.

# Error
```
{
    message: Unexpected error: TypeError: fetch failed,
    name: Error,
    stack:
Error: Unexpected error: TypeError: fetch failed at WorkOSNode.handleHttpError (/app/node_modules/@workos-inc/node/lib/workos.js:179:19) at WorkOSNode.<anonymous> (/app/node_modules/@workos-inc/node/lib/workos.js:135:22) at Generator.throw (<anonymous>) at rejected (/app/node_modules/@workos-inc/node/lib/workos.js:6:65) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
```

# Cause/Solution

The error is being thrown here https://github.com/workos/workos-node/blob/main/src/workos.ts#L236, where instead it could be ``new Error(`Unexpected error: ${error}`, { cause: error })``

**Comment by PaulAsjes** [comment]
Hey there, that's a reasonable request. I'll look into this soon.
