### ISSUE TITLE
Error Ts for user-management.acceptInvitation

### ISSUE THREAD

**Issue by skribascode** [workos/workos-node#1189]
Hi,

There is an error with the Type for acceptInvitation of UserManagement. It does not exist and proposes to replace with getInvitation.

acceptInvitation is however in the Workos documentation.

user-management.d.ts does not contain a type for acceptInvitation

Thanks

Package : "@workos-inc/node": "^7.30.1"

Error TS : 
Property 'acceptInvitation' does not exist on type 'UserManagement'. Isn't it 'getInvitation' instead? ts(2551)
user-management.d.ts(99, 5): 'getInvitation' is declared here.

**Comment by PaulAsjes** [comment]
`acceptInvitation` was added in [v7.35.0](https://github.com/workos/workos-node/releases/tag/v7.35.0). If you update to at least that version you should be able to use it as expected.

**Comment by skribascode** [comment]
Thank you !

**Comment by skribascode** [comment]
Edit :
There is an problem.

sendInvitation return "invitation_01E4ZCR3C56J083X43JQXF3JK5".

Onclick on email, return to my app with "?invitation_token=A9pt4Y44LikTzHP8bpO8pfaU5".

not with "invitation_", only A9pt4Y44LikTzHP8bpO8pfaU5,  for accepInvitation function :

const invitation = await workos.userManagement.acceptInvitation('invitation_01E4ZCR3C56J083X43JQXF3JK5');

i tested with :
const invitation = await workos.userManagement.acceptInvitation(
   `invitation_${invitationToken}`,
);

But not working, id of invitation is not correct
 
 thank's
