### ISSUE TITLE
Missing from Connection Types

### ISSUE THREAD

**Issue by josh-nextstage** [workos/workos-node#575]
I noticed there are a bunch of connections (https://workos.com/docs/reference/sso/connection) missing from the ConnectionType. Is there a reason for this?

```
export enum ConnectionType {
  ADFSSAML = 'ADFSSAML',
  Auth0SAML = 'Auth0SAML',
  AzureSAML = 'AzureSAML',
  GenericOIDC = 'GenericOIDC',
  GenericSAML = 'GenericSAML',
  GoogleOAuth = 'GoogleOAuth',
  GoogleSAML = 'GoogleSAML',
  MagicLink = 'MagicLink',
  OktaSAML = 'OktaSAML',
  OneLoginSAML = 'OneLoginSAML',
  PingFederateSAML = 'PingFederateSAML',
  PingOneSAML = 'PingOneSAML',
  VMwareSAML = 'VMwareSAML',
}
```

**Comment by maxdeviant** [comment]
The possible `ConnectionType` value were updated in https://github.com/workos/workos-node/pull/624 and are available in v2.7.0.

There's also a new PR (#720) adding `LoginGovOidc` currently open that will be available soon.
