### ISSUE TITLE
Allow customization of Axios instance

### ISSUE THREAD

**Issue by gingerich** [workos/workos-node#627]
## Problem
I'm using this SDK in a project running on Cloudflare Workers which is not a native Node runtime. Axios expects either `XMLHttpRequest` or Node's `http` module to be available which causes an error since Cloudflare Workers only supports the standard [Fetch API](https://developers.cloudflare.com/workers/runtime-apis/fetch).

## Proposal
Axios accepts custom adapters to provide the underlying http client implementation. The adapter is specified within [Request Config](https://axios-http.com/docs/req_config). I would like to customize the Axios client instance by passing in additional options to the WorkOS constructor. This could be done by passing in a Axios instance or the Request Config used to create the Axios instance. This would also be useful to create mock implementation for testing.

For example,
```javascript
new WorkOS(key, {
  axios: axios.create({ adapter: myFetchAdapter })
});
```

**Comment by maxdeviant** [comment]
Hey @gingerich, as of v2.12.0 we now support customizing the underlying Axios instance using the `axios` option:

```ts
new WorkOS(key, {
  axios: { adapter: myFetchAdapter },
});
```

**Comment by gingerich** [comment]
@maxdeviant Excellent, thanks for the update.
