### ISSUE TITLE
WorkOS is not a constructor

### ISSUE THREAD

**Issue by koolfreak** [workos/workos-node#628]
const WorkOS = require('@workos-inc/node');

const workos = new WorkOS("sk_test_a2");
TypeError: WorkOS is not a constructor

**Comment by maxdeviant** [comment]
When using CommonJS-style imports you need to import the SDK constructor like so:

```ts
const { WorkOS } = require('@workos-inc/node');

const workos = new WorkOS('sk_example_123456789');
```

**Comment by koolfreak** [comment]
ok thanks, it's working now
