### ISSUE TITLE
Suggestion: allow skipping of verification in `webhooks.constructEvent`

### ISSUE THREAD

**Issue by liaujianjie** [workos/workos-node#708]
My app architecture separates the request authentication from the handling of webhook events.

```
webhook event --> [request authentication layer] --> [controllers] --> [services]
                     ^                                         ^
                     |                                         |
                     where we call `webhooks.verifyHeader`     |
                                                               |
                                                               where we call `webhooks.constructEvent`
```

It would be neat if we could skip or separate the `webhooks.verifyHeader` call from `webhooks.constructEvent`. I'll be happy to make a PR for this.

**Comment by maxdeviant** [comment]
Hi @liaujianjie, it looks like we already expose the `webhooks.verifyHeader` method separately, so you can do the webhook signature verification wherever you want.

In regards to not verifying the header in `webhooks.constructEvent`, the only thing `constructEvent` is going is verifying the header and then casing the payload to the `Webhook` type:

https://github.com/workos/workos-node/blob/91b21e85d97e6cddbb864a6e618cf5ed7aabdd08/src/webhooks/webhooks.ts#L17-L21

So in your case if you don't want to verify the header again you could avoid calling `webhooks.constructEvent` and do `payload as Webhook` yourself.

Does that work for you?

**Comment by liaujianjie** [comment]
Ah yes, that would do the trick. Thank you!
