### ISSUE TITLE
What is the best way to manage Guest access to set of resources (Sharing)

### ISSUE THREAD

**Issue by Fawwaz-2009** [workos/workos-node#957]
Hello 👋 , I'm exploring if workos is a good fit for us and I wanted to ask what are the best practices for implementing resource sharing with WorkOS, similar to how Figma enables users to share a specific design with another user, who then gains access to that design?

**Comment by PaulAsjes** [comment]
Hey there 👋. Please keep GitHub issues for problems with or suggestions for the SDK itself. For product questions you can reach out to WorkOS support directly at support@workos.com.

To answer your question, you'd want to check out the [Directory Sync](https://workos.com/docs/directory-sync) product, specifically the part around SCIM.
