### ISSUE TITLE
Incompatibility with Cloudflare Workers

### ISSUE THREAD

**Issue by Pelps12** [workos/workos-node#964]
Although buffer is globally defined in a node environment, in an edge environment like Cloudflare Workers, Buffer has to be imported as "node:buffer". Frameworks like SvelteKit handle the conversion of "buffer" to "node:buffer" internally [Link](https://github.com/sveltejs/kit/pull/10544). However, in constructEvent, because Buffer is assumed to be globally defined. ![Screenshot 2024-02-17 225517](https://github.com/workos/workos-node/assets/31068338/e5a3ed9b-867e-4a4c-b386-e6ca53217b72) 

When deployed to Cloudflare, my SvelteKit application's webhook errors out with "Buffer not defined"
![Screenshot 2024-02-17 224746](https://github.com/workos/workos-node/assets/31068338/becca90a-5a68-42fd-b8d0-511f5cc13259)

**Comment by benoitgrelard** [comment]
Hey @Pelps12, you are 100% right, that's my bad for letting this one through.
Will have a fix up in a few minutes.

**Comment by benoitgrelard** [comment]
Hey @Pelps12, v6.0.1 has now been published, it contains a few fixes including one for this issue.

https://github.com/workos/workos-node/releases/tag/v6.0.1

**Comment by hieutrluu** [comment]
Hi @benoitgrelard 
the problem seem to have resurfaced

I am using
`"@workos-inc/node": "^7.35.1",`
<img width="1290" alt="Image" src="https://github.com/user-attachments/assets/de57d36e-212c-48ba-87ed-09c2062c7cca" />
