### ISSUE TITLE
Update WorkOS docs for new session endpoints in Node SDK

### ISSUE THREAD

**Issue by chongshengsun** [workos/workos-node#982]
I noticed new session-related endpoints were added to the WorkOS Node SDK in this PR: https://github.com/workos/workos-node/pull/974, please update the docs to help devs understand and integrate the new session features

**Comment by PaulAsjes** [comment]
Hi @chongshengsun, docs are coming very soon! This is an update to get ready for a future launch. See https://workos.com/launch-week/ for more details.
